version: '3.5'
services:
  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=false"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--serverstransport.insecureskipverify=true"
      - "--certificatesresolvers.tesla-tlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.tesla-tlschallenge.acme.email=xbaro@uoc.edu"
      - "--certificatesresolvers.tesla-tlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.tesla-tlschallenge.acme.httpchallenge.entrypoint=http"
      - "--providers.docker.network=tesla_public"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    networks:
      - tesla_public
      - tesla_private
  database:
    volumes:
      - db_volume:/var/lib/mysql
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tesla
      MYSQL_DATABASE: tesla
      MYSQL_USER: tesla
      MYSQL_PASSWORD: tesla
    networks:
      - tesla_private
  vault:
    image: vault
    #command: "server -config /local_config.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.tesla-ce`)"
      - "traefik.http.routers.vault.entrypoints=https"
      - "traefik.http.routers.vault.tls.certresolver=tesla-tlschallenge"
      - "traefik.http.services.vault-service.loadbalancer.server.port=8200"
      - "traefik.http.routers.vault.service=vault-service"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: sRRkAJtED7TmrbSf3zheD3LM
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    networks:
      - tesla_public
      - tesla_private
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - tesla_public
      - tesla_private
  storage:
    image: minio/minio
    volumes:
      - minio_volume:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`storage.tesla-ce`)"
      - "traefik.http.routers.minio.entrypoints=https"
      - "traefik.http.routers.minio.tls.certresolver=tesla-tlschallenge"
      - "traefik.http.services.minio-service.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.service=minio-service"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - tesla_public
      - tesla_private
  rabbitmq:
    image: rabbitmq:management-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.tesla-ce`)"
      - "traefik.http.routers.rabbitmq.entrypoints=https"
      - "traefik.http.routers.rabbitmq.tls.certresolver=tesla-tlschallenge"
      - "traefik.http.services.rabbitmq-service.loadbalancer.server.port=15672"
      - "traefik.http.routers.rabbitmq.service=rabbitmq-service"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - tesla_public
      - tesla_private
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - 5672:5672
volumes:
  db_volume:
    driver_opts:
      type: none
      device: ${PWD}/_data/db
      o: bind
  redis_volume:
    driver_opts:
      type: none
      device: ${PWD}/_data/redis
      o: bind
  minio_volume:
    driver_opts:
      type: none
      device: ${PWD}/_data/minio
      o: bind
  rabbitmq_volume:
    driver_opts:
      type: none
      device: ${PWD}/_data/rabbitmq
      o: bind
  traefik_data:
    driver_opts:
      type: none
      device: ${PWD}/_data/traefik
      o: bind
networks:
  tesla_public:
    external: true
  tesla_private:
    external: true
